### PR TITLE
Refactored authentication and configuration

### PR DESCRIPTION
**Pull request by dorav**
* Improved security, you no longer need to hard-code the credentials to
  pocket
* No more configuration template that you need to copy, input is now
  taken from the user in the first run. The config is saved in the home
  directory
* Removed unused code
* Saved the pocket authentication token so you only need to authenticate
  once with the user
* Removed dependency of the external chrome driver and selenium
  dependencies

### CODE REVIEW

**Comment by aayaffe** [comment]
Great improvement!
One problem though, when pocket authentication finishes this web page appears:
image

**Comment by dorav** [comment]
This happens to you every time or only on the first time?

**Comment by aayaffe** [comment]
only on the first time (easily reproduced after deleting the config file
you created)

**Comment by aayaffe** [comment]
Only on the first time (reproduced after deleting all the config files from user directory)

**Comment by dorav** [comment]
👍

**Pull request merged**
